version: 2
updates:
  # Update Github actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: "THIS_PREVENTS_MY_TEST_DATA_FROM_GETTING_BUMPED"
