# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
  - 3.8
  - 3.7
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis twine readme_renderer[md]

# Command to run tests, e.g. python setup.py test
script: |
    tox
    # check the cli command too
    pip install .
    pypi_minimal_requirements_pinned requirements_dev.txt requirements_dev.txt
    python setup.py sdist bdist_wheel
    twine check dist/*

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: koshi
  password:
    secure: Fgx0xK9OCfgoqqBT3NtYH7dNzaYKp37za5+2aM2S94f8NwGhbUCtgskdnLCzJ/t65Ok5z7lBlMVAkqQZUrv9gy/HJ5tqRaMW9McjqjbGDzYEQXBj/N2Lcrzk9MuFHKZD1R/yjtudzoRBjVCRi4MHx/2r9psVEYenOoRV7YVHmh5lWLPpkq9LcqEu9MnUaqQxi6xWIO3DZn9jmB1vBSCyNQJVgNraXLy7tzZ7d4/F91Noh1figiuAwKBOpz5uGix3zH47YHXbq3xwl9hcus2wgPo0/AXoHhN8UjOCWJYjIAKAam0ILGhYGQ/mhU+tMArxj58172noFatX7qobwchbZxqFIZJxzj1HhBYH5h5MADNjyycDaAl9Stp0GWOxSQKwvfTaXDyONeE76tp1+FSVSMqDjeFntOUxlaD9yTZsAtpgRp+SjNuI/u2e71134+Rb8VEg97lscetuMqErCsPfzO48fglvtq4fn0RKDByBgJkOs1d1hJ0ehsSHENuud7E74Hxg0XYemEwxpwUS+0vQkrsDqsT/OrYLzSAC5DUdy5++refraYDriIyVGShXTM0hMFk799/30sW+YD3Syo3v4SzHRuQwjfxdSOebdD+c4DrLV38orici7M4o9EiG6do5JBV8Vz4uwFTBhtNaa2kjzgPWECDKd3iv4LY3YGvRVcY=
  on:
    tags: true
    repo: renefritze/pypi_oldest_requirements
    # a pure python needs no muliple builds
    python: 3.6
