name: Test Python Package

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.12", "3.10"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v3
    - name: Install dependencies
      run: |
        uv sync --python ${{ matrix.python-version }}  --extra dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        uv run pytest
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: results_${{ matrix.python-version }}
        path: tests/test_pypi_oldest_requirements/
