name: Test Python Package

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.12", "3.10"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v6
    - name: Install dependencies
      run: |
        uv sync --python ${{ matrix.python-version }}  --extra dev
    - name: Test with pytest
      run: |
        uv run pytest
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: results_${{ matrix.python-version }}
        path: tests/test_pypi_oldest_requirements/
